# Generated by Django 5.1.4 on 2025-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_ewidencji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekordSprzetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_osoby', models.CharField(max_length=100, verbose_name='Nazwa osoby')),
                ('nazwa_sprzetu', models.CharField(max_length=100, verbose_name='Nazwa sprzętu')),
                ('numer_seryjny', models.CharField(max_length=100, verbose_name='Numer seryjny')),
                ('nowy_numer_seryjny', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nowy numer seryjny')),
                ('opis_usterki', models.TextField(verbose_name='Opis usterki')),
                ('status', models.CharField(choices=[('CPTI_WAIT', 'Czeka na zawiezienie do CPTI'), ('CPTI', 'w CPTI'), ('PICKUP_WAIT', 'Czeka na odbiór przez ucznia'), ('PICKED_UP', 'odebrany przez ucznia'), ('SELECT', 'Wybierz pozycje'), ('HAWK_WAIT', 'Czeka na zawiezienie do HAWK'), ('HAWK', 'w HAWK'), ('SCRAP', 'Złom'), ('REPAIR', 'Naprawiamy')], default='SELECT', max_length=20, verbose_name='Status')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
        ),
    ]
