# Generated by Django 5.1.4 on 2025-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_ewidencji', '0003_alter_rekordsprzetu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekordsprzetu',
            name='kategoria',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
