# Generated by Django 5.1.4 on 2025-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_ewidencji', '0004_rekordsprzetu_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekordsprzetu',
            name='kategoria',
            field=models.CharField(blank=True, default='Inna', max_length=100, null=True),
        ),
    ]
